"""empty message

Revision ID: 579e46b196d3
Revises: 8db04fecdc1b
Create Date: 2020-09-13 16:59:38.140505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579e46b196d3'
down_revision = '8db04fecdc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'p_language')
    # ### end Alembic commands ###
