"""empty message

Revision ID: dabc86f27792
Revises: 579e46b196d3
Create Date: 2020-09-13 18:31:39.901331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabc86f27792'
down_revision = '579e46b196d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'p_language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('p_language', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
